version: '3.7'
services:
  minirt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "develop_space"
    working_dir: "/home/miniRT"
    #ports:
    volumes:
      - ./src:/home/miniRT/src
      - ./include:/home/miniRT/include
    stdin_open: true
    tty: true
    command: bash -c "/home/miniRT/src/mlx_install.sh && /bin/bash -i"