version: '3.7'
services:
  minirt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "develop_space"
    working_dir: "/home/miniRT"
    #ports:
    volumes:
      - ..:/home/miniRT
      - ./mlx_install.sh:/home/miniRT/mlx_install.sh
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=172.22.4.14:0
    command: bash -c "chmod 777 /home/miniRT/mlx_install.sh&& /home/miniRT/mlx_install.sh && /home/miniRT/mlx_install.sh && /bin/bash -i"